SELECT MEMBER_ID,MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER IN ('W')
AND TLNO <> 'NULL'
AND  DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') LIKE '1%%%-03%' 
ORDER BY MEMBER_ID